### ISSUE TITLE
How can i use this package load a word2vec trained bin-package by python?

### ISSUE THREAD

**Issue by atlantiswqq** [ynqa/wego#45]
I used python to train a word2vec package. I want to use golang for servitization, but I don't know how to load the package I have trained，Anybody have any experience with that？ pls help me，thanks very much

**Comment by ynqa** [comment]
@atlantiswqq Do you want to load trained vectors in Go like `Word2Vec.load` of gensim? Currently, wego outputs a file that is written word vectors with the following format:
```
<word> <value1> <value2> ... <value_dim>
```
But I've not yet created utilities to load them, so please parse them and into some collections.

Or if you want to load gensim object via wego, I have no plans for that...
