### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by RadostinaIvanova** [ynqa/wego#55]
I ran the example with the text8 file and i get the following error

"read 17005207 words 2.4695522s
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc00029a008)
        c:/go/src/runtime/sema.go:56 +0x49
sync.(*WaitGroup).Wait(0xc00029a000)
        c:/go/src/sync/waitgroup.go:130 +0x6b
github.com/ynqa/wego/pkg/model/word2vec.(*word2vec).batchTrain(0xc00007c100, 0x2710, 0xa)
        D:/FMI/golang_workspace/src/github.com/ynqa/wego/pkg/model/word2vec/word2vec.go:176 +0x14c
github.com/ynqa/wego/pkg/model/word2vec.(*word2vec).Train(0xc00007c100, 0x2c32e0, 0xc000006028, 0x0, 0xc000006028)
        D:/FMI/golang_workspace/src/github.com/ynqa/wego/pkg/model/word2vec/word2vec.go:128 +0x5af
main.main()
        D:/FMI/golang_workspace/src/project/main.go:71 +0x1cb

goroutine 50 [chan receive]:............................................."
and so on...
I  have tried my own files with the same format as the one in text8 but I get the same mistake at some time during the execution.
Am I doing something wrong or there is some kind of issue with the example?

**Comment by wujunfeng1** [comment]
This issue might be the same one as https://github.com/ynqa/wego/issues/56.

**Comment by ynqa** [comment]
Fixed in https://github.com/ynqa/wego/pull/58.
